name = "Natural"
license = "MIT"
licenselink = ""
description = "A simple theme for Hugo. That's it"
homepage = "https://github.com/"
tags = ["blog", "clean", "customizable", "dark", "highlighting", "light", "minimal", "monochromatic", "multilingual", "personal", "responsive", "simple", "technical"]
features = ["blog", "shortcode", "syntax Highlighting"]
min_version = 0.01

[author]
  name = "insdram"
  homepage = "https://nuoea.com"
